charms:
  THIS_TEXT_IS_USED_FOR_THE_CHARMS_COMMAND:
    material: PLACEHOLDER
    name: PLACEHOLDER
    lore: ยง4PLACEHOLDER
    glow: false
  breaker:
    material: STICK
    name: ยง8Glass Breaker
    lore: Instantly break glass!
    glow: true