name: MinecraftGlass
version: 2
main: com.github.minecraftglass.MinecraftGlass
description: Implementing new glass utilities in Minecraft!
author: Menou
website: https://hangar.papermc.io/Menou/MinecraftGlass
api-version: 1.21
commands:
  glass:
    description: Give a Glass item or reload the plugin.
    permission: minecraftglass.glass
    permission-message: You cannot use this command.
    usage: /glass <PLAYER> <NAME_OF_ITEM> OR /glass reload