name: MinecraftGlass
version: 1
main: com.github.minecraftglass.MinecraftGlass
description: Implementing new items to work with glass in Minecraft
author: Kiron-Ang
website: https://github.com/Kiron-Ang/MinecraftGlass
api-version: 1.21
commands:
  glass:
    description: Give a Glass item or reload the plugin.
    permission: minecraftglass.glass
    permission-message: You cannot use this command.
    usage: /glass <PLAYER> <NAME_OF_ITEM> OR /glass reload